
project_id = "mqppvcrlvsgrsqelglod"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://mqppvcrlvsgrsqelglod.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true

[functions.amazon-connect-calls]
verify_jwt = true

[functions.amazon-connect-webhook]
verify_jwt = false

[functions.amazon-sns-sms]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-estimate]
verify_jwt = true

[functions.send-team-invitation]
verify_jwt = true

[functions.intelligent-ai-assistant]
verify_jwt = true

[functions.automation-executor]
verify_jwt = true

[functions.reports-run]
verify_jwt = true

[functions.reports-templates]
verify_jwt = true

[functions.exec-sql]
verify_jwt = true

[functions.test-openai]
verify_jwt = true

[functions.update-profiles-schema]
verify_jwt = true
