
project_id = "mqppvcrlvsgrsqelglod"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
tenant_id = "realtime-dev"
max_connections = 100
max_channels_per_client = 100
max_joins_per_second = 100
max_events_per_second = 100
postgres_changes_enabled = true
private_key = "SUPABASE_REALTIME_PRIVATE_KEY"

[storage]
enabled = true
file_size_limit = "50MiB"
s3_enabled = false

[auth]
enabled = true
api_url = "http://kong:8000"
api_url_internal = "http://kong:8000"
default_theme = "default"
external_email_enabled = true
external_phone_enabled = true
external_sms_enabled = true
external_apple_enabled = false
external_azure_enabled = false
external_bitbucket_enabled = false
external_discord_enabled = false
external_facebook_enabled = false
external_figma_enabled = false
external_github_enabled = false
external_gitlab_enabled = false
external_google_enabled = false
external_keycloak_enabled = false
external_linkedin_enabled = false
external_notion_enabled = false
external_twitch_enabled = false
external_twitter_enabled = false
external_slack_enabled = false
external_spotify_enabled = false
external_workos_enabled = false
external_zoom_enabled = false
mailer_templates_enabled = true
mailer_secure_email_change_enabled = true
mailer_autoconfirm = false
mailer_secure_password_change_enabled = true
mailer_otp_exp = 86400
sms_autoconfirm = false
sms_otp_exp = 60
sms_otp_length = 6
password_min_length = 6
external_phone_default_to_phone = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_signup = ""
template_invite = ""
template_magic_link = ""
template_recovery = ""
template_email_change = ""

[auth.sms]
enable_signup = true
template_signup = ""
template_invite = ""
template_magic_link = ""
template_recovery = ""

[edge-runtime]
enabled = true
inspector_port = 8083

[functions.exec-sql]
verify_jwt = true

[functions.generate-with-ai]
verify_jwt = true

[functions.manage-phone-numbers]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.test-openai]
verify_jwt = true

[functions.twilio-calls]
verify_jwt = false

[functions.update-profiles-schema]
verify_jwt = true

[analytics]
enabled = false

[supabase.logs]
level = "info"

[supabase.logs.api]
level = "info"

[supabase.logs.db]
level = "info"

[supabase.logs.auth]
level = "info"

[supabase.logs.storage]
level = "info"

[supabase.logs.edge-runtime]
level = "info"

[supabase.logs.functions]
level = "info"

[supabase.logs.realtime]
level = "info"
